name: Build and deploy Next.js app to Azure Web App - tech0-gen8-step4-pos-app-79

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify repository contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing all files:"
          ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install  # ローカルで依存関係をインストール

      - name: Build Next.js app
        run: npm run build  # `.next/` を生成

      - name: Verify build output
        run: ls -R .next  # ビルド後のファイルを確認

      - name: Prepare deployment package
        run: |
          echo "Creating wwwroot directory..."
          mkdir -p wwwroot
          if [ -d wwwroot ]; then
            echo "wwwroot directory successfully created."
          else
            echo "Failed to create wwwroot directory!" && exit 1
          fi
          echo "Copying build files..."
          cp -r .next package.json package-lock.json next.config.js wwwroot/
          if [ -d public ]; then
            cp -r public wwwroot/
          else
            echo "public/ directory does not exist, skipping..."
          fi
          echo "Deployment package prepared successfully!"

      - name: Verify deployment files before upload
        run: |
          echo "Listing contents of wwwroot:"
          ls -R ./wwwroot

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: wwwroot

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Verify deployment files after download
        run: |
          echo "Listing contents of wwwroot after download:"
          ls -R ./wwwroot

      - name: Install dependencies on Azure
        run: npm install --prefix ./wwwroot  # `wwwroot` で `npm install`

      - name: Test application startup
        run: |
          echo "Running npm start to check for errors..."
          npm --prefix ./wwwroot start || echo "npm start failed!"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen8-step4-pos-app-79'
          slot-name: 'Production'
          package: ./wwwroot
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          clean: true  # 古いファイルを削除
